### ISSUE TITLE
Pridaj tlačítko s linkom na preklad

### ISSUE THREAD

**Issue by ricco386** [microbitsk/microbit.sk-website#4]
**Pridaj tlačítko s linkom na preklad keď sa ukončí issue #3**
Vo footery máme tlačitka s akciami pre používateľa, pridaj tlačítko pre preklady na Crowdin

**Pridaj tlačítko s linkom na preklad dokumentácie**
Vo footery máme tlačitka s akciami pre používateľa, pridaj tlačítko pre preklad dokumentácie: https://crowdin.com/project/bbc-microbit-micropython

**Upravovaný template:**
``microbit.sk-website/templates/body.html``

**Comment by mimmon** [comment]
beriem si tuto issue
